# Generated by Django 3.1.3 on 2020-11-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='Jake', max_length=100),
            preserve_default=False,
        ),
    ]
